name: Test Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Build extension
      run: |
        python build_extension.py

    - name: Verify build output
      shell: bash
      run: |
        ls -lh dist/
        if [ ! -f "dist/phobos_4.zip" ]; then
          echo "Error: phobos_4.zip not found!"
          exit 1
        fi

    - name: Check zip contents
      shell: bash
      run: |
        if command -v unzip &> /dev/null; then
          unzip -l dist/phobos_4.zip | head -20 || true
        elif command -v 7z &> /dev/null; then
          7z l dist/phobos_4.zip | head -30 || true
        else
          echo "Zip verification skipped (no unzip/7z available)"
        fi

    - name: Verify blender_manifest.toml in zip
      shell: bash
      run: |
        if command -v unzip &> /dev/null; then
          unzip -l dist/phobos_4.zip | grep -q "blender_manifest.toml" && echo "✅ blender_manifest.toml found" || exit 1
        elif command -v 7z &> /dev/null; then
          7z l dist/phobos_4.zip | grep -q "blender_manifest.toml" && echo "✅ blender_manifest.toml found" || exit 1
        else
          echo "⚠️ Manifest verification skipped"
        fi

    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-build-${{ matrix.os }}-py${{ matrix.python-version }}
        path: dist/phobos_4.zip
        retention-days: 7
